=== olgaku1/Task_XML/src/main/resources/banks.xsd
<?xml version = "1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.by"
           xmlns="http://www.example.by" elementFormDefault="qualified">


    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[А-Яа-я][A-Za-z]{4,40}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="country">
        <xs:restriction base="xs:string">
            <xs:pattern value="[А-Я][а-я]{2,20}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="До востребования"/>
                <xs:enumeration value="Срочный"/>
                <xs:enumeration value="Расчетный"/>
                <xs:enumeration value="Накопительный"/>
                <xs:enumeration value="Сберегательный"/>
                <xs:enumeration value="Металлический"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="depositor">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[А-Яа-я \s*]{6,60}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="account-id">
        <xs:simpleType>
            <xs:restriction base="xs:nonNegativeInteger"/>
        </xs:simpleType>

    </xs:element>

    <xs:element name="amount-on-deposit" default="0" type="xs:double"/>

    <xs:element name="profitability">
        <xs:simpleType>
            <xs:restriction base="xs:double">
                <xs:minExclusive value="0"/>
                <xs:maxExclusive value="100"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="time-constraints">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="2"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="bank">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="type"/>
                <xs:element ref="depositor"/>
                <xs:element ref="account-id"/>
                <xs:element ref="amount-on-deposit"/>
                <xs:element ref="profitability"/>
                <xs:element ref="time-constraints"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="country" type="xs:string" use="required"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="banks">
        <xs:complexType>
            <xs:sequence>
                <xs:element
                        ref="bank"
                        minOccurs="10"
                        maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== olgaku1/Task_XML/src/main/resources/banks.xml
<?xml version = "1.0"?>

<banks xmlns="http://www.example.by"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.by banks.xsd">


    <bank name="Приорбанк" country="Беларусь">
        <type>До востребования</type>
        <depositor>Десятник Анастасия Анатольевна</depositor>
        <account-id>1</account-id>
        <amount-on-deposit>100</amount-on-deposit>
        <profitability>2.5</profitability>
        <time-constraints>24</time-constraints>
    </bank>

    <bank name="Беларусбанк" country="Беларусь">
        <type>Накопительный</type>
        <depositor>Позняк Ирина Леонидовна</depositor>
        <account-id>2</account-id>
        <amount-on-deposit>840</amount-on-deposit>
        <profitability>1.7</profitability>
        <time-constraints>36</time-constraints>
    </bank>

    <bank name="Приорбанк" country="Беларусь">
        <type>Сберегательный</type>
        <depositor>Топчиева Валентина Петровна</depositor>
        <account-id>3</account-id>
        <amount-on-deposit>1230</amount-on-deposit>
        <profitability>1.5</profitability>
        <time-constraints>60</time-constraints>
    </bank>

    <bank name="Белагропромбанк" country="Беларусь">
        <type>Сберегательный</type>
        <depositor>Жуковская Елена Борисовна</depositor>
        <account-id>4</account-id>
        <amount-on-deposit>845</amount-on-deposit>
        <profitability>5.0</profitability>
        <time-constraints>42</time-constraints>
    </bank>

    <bank name="Беларусбанк" country="Беларусь">
        <type>Накопительный</type>
        <depositor>Костень Сергей Викторович</depositor>
        <account-id>5</account-id>
        <amount-on-deposit>60</amount-on-deposit>
        <profitability>1.7</profitability>
        <time-constraints>24</time-constraints>
    </bank>

    <bank name="Беларусбанк" country="Беларусь">
        <type>Накопительный</type>
        <depositor>Десятник Дмитрий Викторович</depositor>
        <account-id>6</account-id>
        <amount-on-deposit>2650</amount-on-deposit>
        <profitability>1.7</profitability>
        <time-constraints>60</time-constraints>
    </bank>

    <bank name="МТБанк" country="Беларусь">
        <type>Сберегательный</type>
        <depositor>Десятник Анастасия Анатольевна</depositor>
        <account-id>7</account-id>
        <amount-on-deposit>450</amount-on-deposit>
        <profitability>2.3</profitability>
        <time-constraints>36</time-constraints>
    </bank>

    <bank name="МТБанк" country="Беларусь">
        <type>До востребования</type>
        <depositor>Позняк Анатолий Павлович</depositor>
        <account-id>8</account-id>
        <amount-on-deposit>1500</amount-on-deposit>
        <profitability>3.7</profitability>
        <time-constraints>48</time-constraints>
    </bank>

    <bank name="БПС-Сбербанк" country="Беларусь">
        <type>Срочный</type>
        <depositor>Юрчук Дмитрий Александрович</depositor>
        <account-id>9</account-id>
        <amount-on-deposit>520</amount-on-deposit>
        <profitability>0.8</profitability>
        <time-constraints>6</time-constraints>
    </bank>

    <bank name="Технобанк" country="Беларусь">
        <type>Срочный</type>
        <depositor>Новик Андрей Васильевич</depositor>
        <account-id>10</account-id>
        <amount-on-deposit>4500</amount-on-deposit>
        <profitability>1.17</profitability>
        <time-constraints>9</time-constraints>
    </bank>

    <bank name="АльфаБанк" country="Беларусь">
        <type>Накопительный</type>
        <depositor>Грицавец Антон Андреевич</depositor>
        <account-id>11</account-id>
        <amount-on-deposit>180</amount-on-deposit>
        <profitability>2.7</profitability>
        <time-constraints>36</time-constraints>
    </bank>

</banks>
